---

- name: "Find the current date/time"
  shell:
    cmd: date
  register: datetime

- name: "Create a random bootloader password"
  command: yes `openssl rand -base64 48` | grub2-mkpasswd-pbkdf2 | awk '/grub.pbkdf/{print$NF}'
  register: bootloader_pw
  when: randomize_bootloader_pw

- name: "Create specific isolinx.cfg for this machine's UUID {{ newvm.ansible_facts.hw_product_uuid }}"
  template:
    src: isolinux.cfg.j2
    dest: "/var/lib/tftpboot/pxelinx.cfg/{{ newvm.ansible_facts.hw_product_uuid }}"
    mode: '0644'

- name: "Create specific kickstart file"
  template:
    src: ks.cfg.j2
    dest: /var/ftp/pub/{{ newvm.ansible_facts.hw_product_uuid }}_ks.cfg
    mode: '0644'

# http://www.firewalld.org/documentation/howto/add-a-service.html
# firewall-offline-cmd --new-service=myservice
# firewall-offline-cmd --service=service --set-description=description
# firewall-offline-cmd --service=service --set-short=description
# firewall-offline-cmd --service=service --add-port=portid[-portid]/protocol
# firewall-offline-cmd --service=service --add-protocol=protocol
# firewall-offline-cmd --service=service --add-source-port=portid[-portid]/protocol
# firewall-offline-cmd --service=service --add-module=module
# firewall-offline-cmd --service=service --set-destination=ipv:address[/mask]
